/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Availability {
  'status' : { 'pending' : null } |
    { 'onJob' : null } |
    { 'custom' : string } |
    { 'available' : null } |
    { 'unavailable' : null },
  'lastUpdated' : Time,
}
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceType' : string,
  'requester' : Principal,
  'targetLaborer' : Principal,
  'durationHours' : bigint,
  'details' : [] | [string],
  'dateTime' : Time,
  'location' : string,
}
export interface BookingInput {
  'serviceType' : string,
  'targetLaborer' : Principal,
  'durationHours' : bigint,
  'details' : [] | [string],
  'dateTime' : Time,
  'location' : string,
}
export type BookingResponse = { 'ok' : bigint } |
  { 'laborerNotFound' : null } |
  { 'callerNotAuthorizedToBook' : null } |
  { 'invalidFieldValues' : null };
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface LaborerData {
  'id' : Principal,
  'contact' : string,
  'bookings' : Array<Booking>,
  'name' : string,
  'availability' : Availability,
  'skills' : Array<string>,
  'location' : string,
  'services' : Array<Service>,
}
export interface LaborerInput {
  'contact' : string,
  'name' : string,
  'availability' : Availability,
  'skills' : Array<string>,
  'location' : string,
  'services' : Array<Service>,
}
export interface Service {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[BookingInput], BookingResponse>,
  'getBookablesNearLocation' : ActorMethod<
    [string, bigint],
    Array<LaborerData>
  >,
  'getCallerLaborer' : ActorMethod<[], [] | [LaborerData]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLaborerById' : ActorMethod<[Principal], [] | [LaborerData]>,
  'getLaborersByNeighborhood' : ActorMethod<[string], Array<LaborerData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerLaborer' : ActorMethod<[LaborerInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingDetails' : ActorMethod<[bigint, string], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];