/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingInput = IDL.Record({
  'serviceType' : IDL.Text,
  'targetLaborer' : IDL.Principal,
  'durationHours' : IDL.Nat,
  'details' : IDL.Opt(IDL.Text),
  'dateTime' : Time,
  'location' : IDL.Text,
});
export const BookingResponse = IDL.Variant({
  'ok' : IDL.Nat,
  'laborerNotFound' : IDL.Null,
  'callerNotAuthorizedToBook' : IDL.Null,
  'invalidFieldValues' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceType' : IDL.Text,
  'requester' : IDL.Principal,
  'targetLaborer' : IDL.Principal,
  'durationHours' : IDL.Nat,
  'details' : IDL.Opt(IDL.Text),
  'dateTime' : Time,
  'location' : IDL.Text,
});
export const Availability = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'onJob' : IDL.Null,
    'custom' : IDL.Text,
    'available' : IDL.Null,
    'unavailable' : IDL.Null,
  }),
  'lastUpdated' : Time,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const LaborerData = IDL.Record({
  'id' : IDL.Principal,
  'contact' : IDL.Text,
  'bookings' : IDL.Vec(Booking),
  'name' : IDL.Text,
  'availability' : Availability,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'services' : IDL.Vec(Service),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LaborerInput = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'availability' : Availability,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'services' : IDL.Vec(Service),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([BookingInput], [BookingResponse], []),
  'getBookablesNearLocation' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(LaborerData)],
      [],
    ),
  'getCallerLaborer' : IDL.Func([], [IDL.Opt(LaborerData)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLaborerById' : IDL.Func([IDL.Principal], [IDL.Opt(LaborerData)], []),
  'getLaborersByNeighborhood' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LaborerData)],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerLaborer' : IDL.Func([LaborerInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingDetails' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingInput = IDL.Record({
    'serviceType' : IDL.Text,
    'targetLaborer' : IDL.Principal,
    'durationHours' : IDL.Nat,
    'details' : IDL.Opt(IDL.Text),
    'dateTime' : Time,
    'location' : IDL.Text,
  });
  const BookingResponse = IDL.Variant({
    'ok' : IDL.Nat,
    'laborerNotFound' : IDL.Null,
    'callerNotAuthorizedToBook' : IDL.Null,
    'invalidFieldValues' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceType' : IDL.Text,
    'requester' : IDL.Principal,
    'targetLaborer' : IDL.Principal,
    'durationHours' : IDL.Nat,
    'details' : IDL.Opt(IDL.Text),
    'dateTime' : Time,
    'location' : IDL.Text,
  });
  const Availability = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'onJob' : IDL.Null,
      'custom' : IDL.Text,
      'available' : IDL.Null,
      'unavailable' : IDL.Null,
    }),
    'lastUpdated' : Time,
  });
  const Service = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const LaborerData = IDL.Record({
    'id' : IDL.Principal,
    'contact' : IDL.Text,
    'bookings' : IDL.Vec(Booking),
    'name' : IDL.Text,
    'availability' : Availability,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'services' : IDL.Vec(Service),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LaborerInput = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'availability' : Availability,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'services' : IDL.Vec(Service),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([BookingInput], [BookingResponse], []),
    'getBookablesNearLocation' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(LaborerData)],
        [],
      ),
    'getCallerLaborer' : IDL.Func([], [IDL.Opt(LaborerData)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLaborerById' : IDL.Func([IDL.Principal], [IDL.Opt(LaborerData)], []),
    'getLaborersByNeighborhood' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LaborerData)],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerLaborer' : IDL.Func([LaborerInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingDetails' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };