/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LaborerInput {
    contact: string;
    name: string;
    mobileNumber: string;
    availability: Availability;
    skills: Array<string>;
    location: string;
    services: Array<Service>;
}
export type Time = bigint;
export interface Availability {
    status: {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "onJob";
        onJob: null;
    } | {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "available";
        available: null;
    } | {
        __kind__: "unavailable";
        unavailable: null;
    };
    lastUpdated: Time;
}
export interface BookingInput {
    serviceType: string;
    targetLaborer: Principal;
    durationHours: bigint;
    details?: string;
    dateTime: Time;
    location: string;
}
export interface Service {
    name: string;
    priceInInr: bigint;
    description: string;
}
export type BookingResponse = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "laborerNotFound";
    laborerNotFound: null;
} | {
    __kind__: "callerNotAuthorizedToBook";
    callerNotAuthorizedToBook: null;
} | {
    __kind__: "invalidFieldValues";
    invalidFieldValues: null;
};
export interface Booking {
    id: bigint;
    status: BookingStatus;
    serviceType: string;
    requester: Principal;
    targetLaborer: Principal;
    durationHours: bigint;
    details?: string;
    dateTime: Time;
    location: string;
}
export interface LaborerData {
    id: Principal;
    laborId: string;
    contact: string;
    bookings: Array<Booking>;
    name: string;
    mobileNumber: string;
    availability: Availability;
    skills: Array<string>;
    location: string;
    services: Array<Service>;
}
export interface UserProfile {
    name: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(bookingData: BookingInput): Promise<BookingResponse>;
    getAllBookings(): Promise<Array<Booking>>;
    getBookablesNearLocation(location: string, radius: bigint): Promise<Array<LaborerData>>;
    getCallerLaborer(): Promise<LaborerData | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLaborerById(laborerId: Principal): Promise<LaborerData | null>;
    getLaborersByNeighborhood(neighborhood: string): Promise<Array<LaborerData>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerLaborer(laborerInput: LaborerInput): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBookingDetails(bookingId: bigint, details: string): Promise<void>;
    updateBookingStatus(bookingId: bigint, status: BookingStatus): Promise<void>;
}
import type { Availability as _Availability, Booking as _Booking, BookingInput as _BookingInput, BookingResponse as _BookingResponse, BookingStatus as _BookingStatus, LaborerData as _LaborerData, LaborerInput as _LaborerInput, Service as _Service, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<BookingResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BookingResponse_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BookingResponse_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookablesNearLocation(arg0: string, arg1: bigint): Promise<Array<LaborerData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookablesNearLocation(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookablesNearLocation(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerLaborer(): Promise<LaborerData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerLaborer();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerLaborer();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLaborerById(arg0: Principal): Promise<LaborerData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaborerById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaborerById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLaborersByNeighborhood(arg0: string): Promise<Array<LaborerData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaborersByNeighborhood(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaborersByNeighborhood(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerLaborer(arg0: LaborerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerLaborer(to_candid_LaborerInput_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerLaborer(to_candid_LaborerInput_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBookingDetails(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingDetails(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingDetails(arg0, arg1);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Availability_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Availability): Availability {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BookingResponse_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingResponse): BookingResponse {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LaborerData_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LaborerData): LaborerData {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LaborerData]): LaborerData | null {
    return value.length === 0 ? null : from_candid_LaborerData_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    laborId: string;
    contact: string;
    bookings: Array<_Booking>;
    name: string;
    mobileNumber: string;
    availability: _Availability;
    skills: Array<string>;
    location: string;
    services: Array<_Service>;
}): {
    id: Principal;
    laborId: string;
    contact: string;
    bookings: Array<Booking>;
    name: string;
    mobileNumber: string;
    availability: Availability;
    skills: Array<string>;
    location: string;
    services: Array<Service>;
} {
    return {
        id: value.id,
        laborId: value.laborId,
        contact: value.contact,
        bookings: from_candid_vec_n7(_uploadFile, _downloadFile, value.bookings),
        name: value.name,
        mobileNumber: value.mobileNumber,
        availability: from_candid_Availability_n16(_uploadFile, _downloadFile, value.availability),
        skills: value.skills,
        location: value.location,
        services: value.services
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        onJob: null;
    } | {
        custom: string;
    } | {
        available: null;
    } | {
        unavailable: null;
    };
    lastUpdated: _Time;
}): {
    status: {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "onJob";
        onJob: null;
    } | {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "available";
        available: null;
    } | {
        __kind__: "unavailable";
        unavailable: null;
    };
    lastUpdated: Time;
} {
    return {
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    serviceType: string;
    requester: Principal;
    targetLaborer: Principal;
    durationHours: bigint;
    details: [] | [string];
    dateTime: _Time;
    location: string;
}): {
    id: bigint;
    status: BookingStatus;
    serviceType: string;
    requester: Principal;
    targetLaborer: Principal;
    durationHours: bigint;
    details?: string;
    dateTime: Time;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n10(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        requester: value.requester,
        targetLaborer: value.targetLaborer,
        durationHours: value.durationHours,
        details: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.details)),
        dateTime: value.dateTime,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    onJob: null;
} | {
    custom: string;
} | {
    available: null;
} | {
    unavailable: null;
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "onJob";
    onJob: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "available";
    available: null;
} | {
    __kind__: "unavailable";
    unavailable: null;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "onJob" in value ? {
        __kind__: "onJob",
        onJob: value.onJob
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "available" in value ? {
        __kind__: "available",
        available: value.available
    } : "unavailable" in value ? {
        __kind__: "unavailable",
        unavailable: value.unavailable
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    laborerNotFound: null;
} | {
    callerNotAuthorizedToBook: null;
} | {
    invalidFieldValues: null;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "laborerNotFound";
    laborerNotFound: null;
} | {
    __kind__: "callerNotAuthorizedToBook";
    callerNotAuthorizedToBook: null;
} | {
    __kind__: "invalidFieldValues";
    invalidFieldValues: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "laborerNotFound" in value ? {
        __kind__: "laborerNotFound",
        laborerNotFound: value.laborerNotFound
    } : "callerNotAuthorizedToBook" in value ? {
        __kind__: "callerNotAuthorizedToBook",
        callerNotAuthorizedToBook: value.callerNotAuthorizedToBook
    } : "invalidFieldValues" in value ? {
        __kind__: "invalidFieldValues",
        invalidFieldValues: value.invalidFieldValues
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LaborerData>): Array<LaborerData> {
    return value.map((x)=>from_candid_LaborerData_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Availability_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Availability): _Availability {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_BookingInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_LaborerInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LaborerInput): _LaborerInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    name: string;
    mobileNumber: string;
    availability: Availability;
    skills: Array<string>;
    location: string;
    services: Array<Service>;
}): {
    contact: string;
    name: string;
    mobileNumber: string;
    availability: _Availability;
    skills: Array<string>;
    location: string;
    services: Array<_Service>;
} {
    return {
        contact: value.contact,
        name: value.name,
        mobileNumber: value.mobileNumber,
        availability: to_candid_Availability_n25(_uploadFile, _downloadFile, value.availability),
        skills: value.skills,
        location: value.location,
        services: value.services
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "onJob";
        onJob: null;
    } | {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "available";
        available: null;
    } | {
        __kind__: "unavailable";
        unavailable: null;
    };
    lastUpdated: Time;
}): {
    status: {
        pending: null;
    } | {
        onJob: null;
    } | {
        custom: string;
    } | {
        available: null;
    } | {
        unavailable: null;
    };
    lastUpdated: _Time;
} {
    return {
        status: to_candid_variant_n27(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: string;
    targetLaborer: Principal;
    durationHours: bigint;
    details?: string;
    dateTime: Time;
    location: string;
}): {
    serviceType: string;
    targetLaborer: Principal;
    durationHours: bigint;
    details: [] | [string];
    dateTime: _Time;
    location: string;
} {
    return {
        serviceType: value.serviceType,
        targetLaborer: value.targetLaborer,
        durationHours: value.durationHours,
        details: value.details ? candid_some(value.details) : candid_none(),
        dateTime: value.dateTime,
        location: value.location
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "onJob";
    onJob: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "available";
    available: null;
} | {
    __kind__: "unavailable";
    unavailable: null;
}): {
    pending: null;
} | {
    onJob: null;
} | {
    custom: string;
} | {
    available: null;
} | {
    unavailable: null;
} {
    return value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "onJob" ? {
        onJob: value.onJob
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "available" ? {
        available: value.available
    } : value.__kind__ === "unavailable" ? {
        unavailable: value.unavailable
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
